### ISSUE TITLE
Is there any option to list the size of each file in the tree formation?

### ISSUE THREAD

**Issue by AkatQuas** [markthree/go-get-folder-size#1]

**Comment by markthree** [comment]
@AkatQuas Sorry, this library does not have this function and will not be added in the future, because it has only one purpose to quickly calculate the size, and the information is redundant。

**Comment by markthree** [comment]
@AkatQuas Nodejs' io is actually very fast, and the bottleneck is mainly in computing performance. If you just want to gradually obtain the size of the number of files from the terminal, Nodejs is enough, and there are more open source libraries to help you.
