### ISSUE TITLE
Error: Cannot find module 'node:buffer'

### ISSUE THREAD

**Issue by wll8** [markthree/go-get-folder-size#2]
- os: win10 x64
- node: 14.15.5

``` txt
>npx go-get-folder-size
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'node:buffer'
Require stack:
```

Please use a method compatible with lower version nodejs

**Comment by markthree** [comment]
@wll8 Hello, pretty boy, handled

you can use it now

```shell
npx go-get-folder-size@v0.2.5
```
or

```shell
npx go-get-folder-size@latest
```

Specific commit can be seen → [7a2df8](https://github.com/markthree/go-get-folder-size/commit/7a2df8ba96fd4014c8995949f17e386f1196e25e)
