### ISSUE TITLE
Can such a fast method be applied to globby?

### ISSUE THREAD

**Issue by wll8** [markthree/go-get-folder-size#3]
go-get-folder-size has obtained the occupied space of the file, so it should also obtain all the file addresses. In the same directory, it took 6 seconds for globby to get the file, but it took 1 second for go-get-folder-size.

**Comment by markthree** [comment]
@wll8 It can be realized in theory, but I don't guarantee it is faster than nodejs because communication takes time，The final result still needs bench。

[go-get-folder-size](https://github.com/markthree/go-get-folder-size) actually only transmits the final result, so it is very fast 🥰

**Comment by wll8** [comment]
It would be great if it implements a .gitignore-compliant file scanner that only outputs file or folder addresses, and if it's fast too. This way I can use it to implement a file synchronization tool.

**Comment by markthree** [comment]
@wll8 In continuous development, look forward to it 👉 [go-globby](https://github.com/markthree/go-globby)

**Comment by markthree** [comment]
@wll8  👉 [fast-cpy](https://github.com/markthree/fast-cpy) can also be used for simple synchronization，Support node stream and go native, also very fast。However, specific files cannot be ignored

**Comment by wll8** [comment]
> fast-cpy

No, I need `copy('D:/', 'http://server/store', {watch: true})`  🙄🐶

> go-globby
Waiting for you to implement cross-platform high-performance globby.

**Comment by markthree** [comment]
> No, I need `copy('D:/', 'http://server/store', {watch: true})` 🙄🐶

nice idea！！That sounds cool. 🥰

**Comment by markthree** [comment]
@wll8 The first version has been implemented, visible [go-globby](https://github.com/markthree/go-globby)
