### ISSUE TITLE
Worker exits from a panic: open [PATH]: Access is denied

### ISSUE THREAD

**Issue by Mimexe** [markthree/go-get-folder-size#4]
Hello,
I am wondering if there is anything that can just skip the file
Thanks

**Comment by markthree** [comment]
@Mimexe The permission problem was not noticed in the previous implementation, and it may be fixed later

**Comment by markthree** [comment]
@Mimexe You can temporarily try  [go-globby](https://github.com/markthree/go-globby) to achieve your needs。

**Comment by markthree** [comment]
Here is a simple example 👇
```ts
import { lstat } from "node:fs/promises";
import { globbyBin } from "go-globby";

const paths = await globbyBin([
  "node_modules/**/*",
  "!node_modules/@types/**/*" // Ignored
]);

console.log(paths)

const sizes = await Promise.all(paths.map(async (p) => {
  const stat = await lstat(p);
  return stat.size;
}));

const total = sizes.reduce((l, r) => l + r)

console.log(total)
```

**Comment by markthree** [comment]
@Mimexe hello，you can use `loose` now 👉 [go-get-folder-size#loose](https://github.com/markthree/go-get-folder-size#loose)
